## Arrays vs. Lists

In [2]:
import numpy as np

# Python list approach — requires a loop
values = [1, 2, 3, 4, 5]
doubled = [x * 2 for x in values]

# NumPy approach — operates on the whole array at once
arr = np.array([1, 2, 3, 4, 5])
doubled = arr * 2
print(doubled)

# Output: [ 2  4  6  8 10]

[ 2  4  6  8 10]


## Creating NumPy Arrays

In [3]:
import numpy as np

# 1-D array
temps = np.array([72.1, 68.4, 74.5, 70.2, 69.8])

# 2-D array (3 rows, 4 columns)
grid = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print(grid.shape)   # (3, 4) — 3 rows, 4 columns
print(grid.dtype)   # int64 — all elements are integers
print(grid.size)    # 12 — total number of elements

(3, 4)
int64
12


## NumPy Array Creation Shortcuts

In [4]:
np.zeros((3, 3))      # 3x3 array of zeros
np.ones((2, 5))       # 2x5 array of ones
np.arange(0, 10, 2)   # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)  # [0.0, 0.25, 0.5, 0.75, 1.0]

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Basic Array Math

In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr.mean())  # 30.0
print(arr.sum())   # 150
print(arr.min())   # 10
print(arr.max())   # 50
print(arr.std())   # Standard deviation: 14.14...

30.0
150
10
50
14.142135623730951


## Creating a DataFrame

In [6]:
import pandas as pd

data = {
    'name': ['Alice', 'Bob', 'Carol', 'Dave'],
    'age': [25, 32, 28, 45],
    'score': [88.5, 92.0, 79.5, 85.0]
}

df = pd.DataFrame(data)
print(df)

    name  age  score
0  Alice   25   88.5
1    Bob   32   92.0
2  Carol   28   79.5
3   Dave   45   85.0


## Getting the Lay of the Land

In [ ]:
import pandas as pd

# Load the Titanic dataset for these examples
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print(df.shape)      # (891, 12) — 891 rows, 12 columns
print(df.shape)  # (891, 12) — 891 rows, 12 columns
print(df.dtypes)  # data type of each column
print(df.head())  # first 5 rows
print(df.tail())  # last 5 rows
print(df.describe())  # summary statistics for numeric columns
print(df.info())  # column names, types, and non-null counts

(891, 12)
(891, 12)
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object
   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch  

# Finding and removing duplicates

In [9]:
import pandas as pd

df = pd.DataFrame(
    {"name": ["Alice", "Bob", "Carol", "Bob"], "score": [88.5, 92.0, 79.5, 92.0]}
)

# Find duplicate rows — returns True for duplicates
print(df.duplicated())
# 0    False
# 1    False
# 2    False
# 3     True

# Show only the duplicated rows
print(df[df.duplicated()])

# Remove duplicates, keeping the first occurrence
df_clean = df.drop_duplicates()
print(df_clean)

0    False
1    False
2    False
3     True
dtype: bool
  name  score
3  Bob   92.0
    name  score
0  Alice   88.5
1    Bob   92.0
2  Carol   79.5


# Creating a datamap

In [11]:
import pandas as pd
import numpy as np

# Load the Titanic dataset for these examples
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# Group by a categorical column and get stats on a numeric column
group_stats = df.groupby("Pclass")["Fare"].describe()
print(group_stats)

        count       mean        std  min       25%      50%   75%       max
Pclass                                                                     
1       216.0  84.154687  78.380373  0.0  30.92395  60.2875  93.5  512.3292
2       184.0  20.662183  13.417399  0.0  13.00000  14.2500  26.0   73.5000
3       491.0  13.675550  11.778142  0.0   7.75000   8.0500  15.5   69.5500


# Finding missing values

In [13]:
import pandas as pd
import numpy as np

s = pd.Series([10, 20, np.nan, 40, None])

print(s.isnull())
# 0    False
# 1    False
# 2     True
# 3    False
# 4     True

# Count missing values per column in a DataFrame
print(df.isnull().sum())

0    False
1    False
2     True
3    False
4     True
dtype: bool
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


# Option 1: Drop the rows (or columns) with missing values

In [14]:
df_clean = df.dropna()  # drop any row with at least one NaN
df_clean = df.dropna(axis=1)  # drop any column with at least one NaN

# Option 2: Fill missing values with a fixed value.

In [15]:
# Fill a numeric column's NaN values with the column mean
df["Age"] = df["Age"].fillna(df["Age"].mean())

# Fill a text column's NaN values with a placeholder
df["Cabin"] = df["Cabin"].fillna("Unknown")

# Option 3: Impute using a model

In [ ]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer

data = pd.DataFrame({"age": [25, np.nan, 32, 41, np.nan, 28]})

imp = SimpleImputer(strategy="mean")
imp.fit(data)
data_filled = imp.transform(data)
print(data_filled)

[[25. ]
 [31.5]
 [32. ]
 [41. ]
 [31.5]
 [28. ]]


# Slicing rows

In [17]:
x = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [11, 12, 13],
            [14, 15, 16],
            [17, 18, 19],
        ],
        [[21, 22, 23], [24, 25, 26], [27, 28, 29]],
    ]
)
x[1]

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

# Slicing columns

In [18]:
x = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [11, 12, 13],
            [14, 15, 16],
            [17, 18, 19],
        ],
        [[21, 22, 23], [24, 25, 26], [27, 28, 29]],
    ]
)
x[:, 1]

array([[ 4,  5,  6],
       [14, 15, 16],
       [24, 25, 26]])

# Dicing

In [19]:
x = np.array(
    [
        [
            [1, 2, 3],
            [4, 5, 6],
            [7, 8, 9],
        ],
        [
            [11, 12, 13],
            [14, 15, 16],
            [17, 18, 19],
        ],
        [[21, 22, 23], [24, 25, 26], [27, 28, 29]],
    ]
)
print(x[1, 1])
print(x[:, 1, 1])
print(x[1, :, 1])
print(f"\n{x[1:2, 1:2]}")

[14 15 16]
[ 5 15 25]
[12 15 18]

[[[14 15 16]]]


# Putting it together

In [20]:
import pandas as pd
import numpy as np

# Load the data
url ="https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

# 1. Get the lay of the land
print(f"Shape: {df.shape}")
print(f"\nMissing values:\n{df.isnull().sum()}")

# 2. Drop duplicates
df = df.drop_duplicates()

# 3. Handle missing values
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Embarked'] = df['Embarked'].fillna('S')  # most common port
df = df.drop(columns=['Cabin'])  # too many missing to be useful

# 4. Select the columns we care about
df = df[['Survived', 'Pclass', 'Sex', 'Age', 'Fare']]

# 5. Aggregate: survival rate by class
print("\nSurvival rate by passenger class:")
print(df.groupby('Pclass')['Survived'].mean().round(2))

Shape: (891, 12)

Missing values:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Survival rate by passenger class:
Pclass
1    0.63
2    0.47
3    0.24
Name: Survived, dtype: float64
